#!/usr/bin/env python3
"""Stage 1 experiment runner.

Loads data from exported JSON (generated by generate_synthetic_dataset.py).
Falls back to generating a fresh small dataset if JSON not found.

Usage:
    python scripts/run_stage1.py --user_id U0001 --goal_id G-U0001-01
    python scripts/run_stage1.py --user_id U0001 --goal_id G-U0001-01 --expand
    python scripts/run_stage1.py --auto   # pick first user/goal automatically
"""
from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.utils.logging_utils import setup_logging
setup_logging()

import logging
from app.config import DEFAULT_CONFIG
from app.data_generation.dataset_builder import build_dataset
from app.data_generation.export_utils import load_dataset_from_json
from app.evaluation.ranking_metrics import compute_all_metrics
from app.pipeline.stage1_ranking_pipeline import Stage1Pipeline
from app.schemas import GoalLogLabel, ResearchGoal, ResearchLog

logger = logging.getLogger(__name__)

_DEFAULT_DATA_DIR = "data/synthetic"


def load_data(data_dir: str) -> tuple[list[ResearchGoal], list[ResearchLog], list[GoalLogLabel]]:
    """Load from JSON if available, otherwise generate small dataset."""
    goals_path = Path(data_dir) / "goals.json"
    if goals_path.exists():
        logger.info("Loading dataset from %s", data_dir)
        _, goals, logs, labels = load_dataset_from_json(data_dir)
    else:
        logger.info("No dataset found at %s. Generating small dataset...", data_dir)
        ds = build_dataset(small_mode=True, seed=42)
        goals, logs, labels = ds.goals, ds.logs, ds.labels
    return goals, logs, labels


def main() -> None:
    parser = argparse.ArgumentParser(description="Run Stage 1 Retrieval Experiment")
    parser.add_argument("--user_id", default=None)
    parser.add_argument("--goal_id", default=None)
    parser.add_argument("--top_k", type=int, default=10)
    parser.add_argument("--expand", action="store_true", help="Enable query expansion variant")
    parser.add_argument("--auto", action="store_true", help="Auto-pick first user/goal")
    parser.add_argument("--data_dir", default=_DEFAULT_DATA_DIR)
    args = parser.parse_args()

    goals, logs, labels = load_data(args.data_dir)

    # Resolve user_id / goal_id
    if args.auto or (args.user_id is None and args.goal_id is None):
        target_goal = goals[0]
    elif args.goal_id:
        target_goal = next((g for g in goals if g.goal_id == args.goal_id), None)
        if target_goal is None:
            logger.error("goal_id=%s not found.", args.goal_id)
            sys.exit(1)
    else:
        target_goal = next((g for g in goals if g.user_id == args.user_id), None)
        if target_goal is None:
            logger.error("No goals found for user_id=%s.", args.user_id)
            sys.exit(1)

    user_id = target_goal.user_id
    user_logs = [l for l in logs if l.user_id == user_id]
    user_labels = [lb for lb in labels if lb.user_id == user_id and lb.goal_id == target_goal.goal_id]

    logger.info("User: %s | Goal: %s (%s) | Logs: %d", user_id, target_goal.goal_id, target_goal.title, len(user_logs))

    cfg = DEFAULT_CONFIG.stage1
    cfg.retrieval.top_k = args.top_k
    # candidate_size: top-N pruning — use ~60% of corpus, minimum top_k * 3
    cfg.retrieval.candidate_size = max(args.top_k * 3, min(len(user_logs) * 6 // 10, 30))

    pipeline = Stage1Pipeline(config=cfg)
    pipeline.index(user_logs)
    result = pipeline.run(target_goal, use_expansion=args.expand)

    print("\n" + "=" * 60)
    print(f"Stage 1  |  Goal: {result.goal.title}")
    print(f"Category : {target_goal.goal_id}")
    print(f"Query    : {result.query_text}")
    print(f"Expand   : {result.used_expansion}")
    print(f"Corpus   : {len(user_logs)} logs")
    print("=" * 60)

    print(f"\n[Top-{args.top_k} Selected Logs]")
    for r in result.selected_logs:
        strength = r.log.metadata.get("evidence_strength", "-")
        print(f"  [{r.rank:2d}] score={r.final_score:.4f}  {r.log.date}  [{strength}]  {r.log.title}")

    if user_labels:
        all_types = {l.activity_type for l in user_logs}
        metrics = compute_all_metrics(result.selected_logs, user_labels, k=args.top_k, all_activity_types=all_types)
        print(f"\n[Metrics @ k={args.top_k}]")
        for name, val in metrics.items():
            print(f"  {name}: {val:.4f}")

        # Label distribution in selected
        label_map = {lb.log_id: lb.label for lb in user_labels}
        dist: dict[str, int] = {}
        for r in result.selected_logs:
            lbl = label_map.get(r.log_id, "unknown")
            dist[lbl] = dist.get(lbl, 0) + 1
        print(f"\n[Label dist in selected] {dist}")
    else:
        print("\n[No labels found for this goal — skipping metrics]")


if __name__ == "__main__":
    main()
