#!/usr/bin/env python3
"""Stage 1 experiment runner.

Loads data from exported JSON (generated by generate_synthetic_dataset.py).
Falls back to generating a fresh small dataset if JSON not found.

Usage:
    python scripts/run_stage1.py --goal_id G-U0001-01 --baseline ours
    python scripts/run_stage1.py --goal_id G-U0001-01 --baseline bm25 --save_result
    python scripts/run_stage1.py --auto --baseline ours_wo_lexical_gate

Baselines:
  bm25               BM25 only, no gate, no expansion
  dense              Dense only, no gate, no expansion
  hybrid             BM25+Dense, no gate, no expansion
  hybrid_expand      BM25+Dense+expansion, no gate
  ours               Full pipeline (default)
  ours_wo_lexical_gate  Full pipeline minus Goal Lexical Gate
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from dotenv import load_dotenv
load_dotenv()

from app.utils.logging_utils import setup_logging
setup_logging()

import logging
from app.config import DEFAULT_CONFIG
from app.data_generation.dataset_builder import build_dataset
from app.data_generation.export_utils import load_dataset_from_json
from app.evaluation.ranking_metrics import (
    compute_all_metrics,
    f1_at_k,
    false_positive_rate,
    selected_precision as calc_selected_precision,
)
from app.pipeline.stage1_ranking_pipeline import Stage1Pipeline
from app.retrieval.candidate_retrieval import RetrievalMode
from app.schemas import GoalLogLabel, ResearchGoal, ResearchLog

logger = logging.getLogger(__name__)

_DEFAULT_DATA_DIR = "data/synthetic"

# ── Baseline configuration table ──────────────────────────────────────────────

STAGE1_BASELINE_CONFIGS: dict[str, dict] = {
    "bm25": {
        "retrieval_mode": RetrievalMode.SPARSE,
        "use_expansion": False,
        "disable_lexical_gate": True,
    },
    "dense": {
        "retrieval_mode": RetrievalMode.DENSE,
        "use_expansion": False,
        "disable_lexical_gate": True,
    },
    "hybrid": {
        "retrieval_mode": RetrievalMode.HYBRID,
        "use_expansion": False,
        "disable_lexical_gate": True,
    },
    "hybrid_expand": {
        "retrieval_mode": RetrievalMode.HYBRID,
        "use_expansion": True,
        "disable_lexical_gate": True,
    },
    "ours": {
        "retrieval_mode": RetrievalMode.HYBRID,
        "use_expansion": True,
        "disable_lexical_gate": False,
    },
    "ours_wo_lexical_gate": {
        "retrieval_mode": RetrievalMode.HYBRID,
        "use_expansion": True,
        "disable_lexical_gate": True,
    },
}


def load_data(data_dir: str):
    goals_path = Path(data_dir) / "goals.json"
    if goals_path.exists():
        logger.info("Loading dataset from %s", data_dir)
        _, goals, logs, labels = load_dataset_from_json(data_dir)
    else:
        logger.info("No dataset found at %s. Generating small dataset...", data_dir)
        ds = build_dataset(small_mode=True, seed=42)
        goals, logs, labels = ds.goals, ds.logs, ds.labels
    return goals, logs, labels


def main() -> None:
    parser = argparse.ArgumentParser(description="Run Stage 1 Retrieval Experiment")
    parser.add_argument("--user_id", default=None)
    parser.add_argument("--goal_id", default=None)
    parser.add_argument("--top_k", type=int, default=10)
    parser.add_argument(
        "--expand", action="store_true",
        help="[deprecated] Use --baseline hybrid_expand or ours instead. "
             "When --baseline=ours, this flag still forces expansion.",
    )
    parser.add_argument("--auto", action="store_true", help="Auto-pick first user/goal")
    parser.add_argument("--data_dir", default=_DEFAULT_DATA_DIR)
    parser.add_argument(
        "--real_embeddings", action="store_true",
        help="Use Gemini Embedding API (requires GEMINI_API_KEY)",
    )
    parser.add_argument(
        "--baseline",
        choices=list(STAGE1_BASELINE_CONFIGS.keys()),
        default="ours",
        help="Baseline mode (default: ours)",
    )
    parser.add_argument(
        "--save_result", action="store_true",
        help="Save result to results/stage1/{goal_id}_{baseline}.json",
    )
    args = parser.parse_args()

    goals, logs, labels = load_data(args.data_dir)

    # ── Resolve target goal ────────────────────────────────────────────────────
    if args.auto or (args.user_id is None and args.goal_id is None):
        target_goal = goals[0]
    elif args.goal_id:
        target_goal = next((g for g in goals if g.goal_id == args.goal_id), None)
        if target_goal is None:
            logger.error("goal_id=%s not found.", args.goal_id)
            sys.exit(1)
    else:
        target_goal = next((g for g in goals if g.user_id == args.user_id), None)
        if target_goal is None:
            logger.error("No goals found for user_id=%s.", args.user_id)
            sys.exit(1)

    user_id = target_goal.user_id
    user_logs = [l for l in logs if l.user_id == user_id]
    user_labels = [
        lb for lb in labels
        if lb.user_id == user_id and lb.goal_id == target_goal.goal_id
    ]

    logger.info(
        "User: %s | Goal: %s (%s) | Logs: %d",
        user_id, target_goal.goal_id, target_goal.title, len(user_logs),
    )

    # ── Baseline config ────────────────────────────────────────────────────────
    baseline = args.baseline
    bcfg = dict(STAGE1_BASELINE_CONFIGS[baseline])  # copy

    # --expand back-compat: forces expansion for 'ours' baseline
    if args.expand and baseline == "ours":
        bcfg["use_expansion"] = True

    cfg = DEFAULT_CONFIG.stage1
    cfg.retrieval.top_k = args.top_k
    cfg.retrieval.candidate_size = max(args.top_k * 3, min(len(user_logs) * 6 // 10, 30))

    pipeline = Stage1Pipeline(
        config=cfg,
        use_real_embeddings=args.real_embeddings,
        retrieval_mode=bcfg["retrieval_mode"],
        disable_lexical_gate=bcfg["disable_lexical_gate"],
    )
    pipeline.index(user_logs)
    result = pipeline.run(target_goal, use_expansion=bcfg["use_expansion"])

    k = args.top_k
    print("\n" + "=" * 60)
    print(f"Stage 1  |  Goal: {result.goal.title}")
    print(f"Baseline : {baseline}")
    print(f"Category : {target_goal.goal_id}")
    print(f"Query    : {result.query_text}")
    print(f"Expand   : {result.used_expansion}")
    print(f"Corpus   : {len(user_logs)} logs")
    print("=" * 60)

    print(f"\n[Top-{k} Selected Logs]")
    for r in result.selected_logs:
        strength = r.log.metadata.get("evidence_strength", "-")
        reason = r.admission_reason or "-"
        print(f"  [{r.rank:2d}] score={r.final_score:.4f}  {r.log.date}  [{strength}]  {r.log.title}")
        print(f"       admission: {reason}")

    if user_labels:
        all_types = {l.activity_type for l in user_logs}
        metrics = compute_all_metrics(
            result.ranked_logs, user_labels,
            k=k,
            all_activity_types=all_types,
            selected_logs=result.selected_logs,
        )
        s_prec = metrics["selected_precision"]
        s_count = metrics["selected_count"]
        fpr = metrics["false_positive_rate"]
        f1 = metrics[f"f1@{k}"]

        print(f"\n[Metrics @ k={k}]")
        print(f"  {'recall@'+str(k):<28} {metrics[f'recall@{k}']:.4f}")
        print(f"  {'precision@'+str(k):<28} {metrics[f'precision@{k}']:.4f}")
        print(f"  {'selected_count':<28} {s_count}")
        print(f"  {'selected_precision':<28} {s_prec:.4f}")
        print(f"  {'f1@'+str(k):<28} {f1:.4f}")
        print(f"  {'false_positive_rate':<28} {fpr:.4f}")
        print(f"  {'mrr':<28} {metrics['mrr']:.4f}")
        print(f"  {'ndcg@'+str(k):<28} {metrics[f'ndcg@{k}']:.4f}")
        print(f"  {'diversity_coverage':<28} {metrics['diversity_coverage']:.4f}")

        label_map = {lb.log_id: lb.label for lb in user_labels}
        dist: dict[str, int] = {}
        for r in result.selected_logs:
            lbl = label_map.get(r.log_id, "unknown")
            dist[lbl] = dist.get(lbl, 0) + 1
        print(f"\n[Label dist in selected] {dist}")

        if args.save_result:
            from app.evaluation.result_writer import save_stage1_result
            path = save_stage1_result(
                goal_id=target_goal.goal_id,
                baseline=baseline,
                metrics={
                    f"recall@{k}": metrics[f"recall@{k}"],
                    f"precision@{k}": metrics[f"precision@{k}"],
                    "selected_count": s_count,
                    "selected_precision": s_prec,
                    f"f1@{k}": f1,
                    "false_positive_rate": fpr,
                    "mrr": metrics["mrr"],
                    f"ndcg@{k}": metrics[f"ndcg@{k}"],
                    "diversity_coverage": metrics["diversity_coverage"],
                },
                selected_log_ids=[r.log_id for r in result.selected_logs],
                selected_titles=[r.log.title for r in result.selected_logs],
                extra={"baseline_config": {k2: str(v) for k2, v in bcfg.items()}},
            )
            print(f"\n[Result saved] {path}")
    else:
        print("\n[No labels found for this goal — skipping metrics]")


if __name__ == "__main__":
    main()
