#!/usr/bin/env python3
"""Stage 1 experiment runner.

Loads data from exported JSON (generated by generate_synthetic_dataset.py).
Falls back to generating a fresh small dataset if JSON not found.

Usage:
    python scripts/run_stage1.py --goal_id G-U0001-01 --baseline ours
    python scripts/run_stage1.py --goal_id G-U0001-01 --baseline dense --save_result
    python scripts/run_stage1.py --auto --baseline ours_wo_lexical_gate

Baselines:
  dense              Dense only, no gate, no expansion
  dense_expand       Dense + query expansion, no gate
  ours               Full pipeline (default)
  ours_wo_lexical_gate  Full pipeline minus Goal Lexical Gate
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from dotenv import load_dotenv
load_dotenv()

from app.utils.logging_utils import setup_logging
setup_logging()

import logging
from app.config import DEFAULT_CONFIG
from app.data_generation.dataset_builder import build_dataset
from app.data_generation.export_utils import load_dataset_from_json
from app.evaluation.ranking_metrics import (
    compute_all_metrics,
    compute_candidate_metrics,
    f1_at_k,
    false_positive_rate,
    selected_precision as calc_selected_precision,
)
from app.pipeline.stage1_ranking_pipeline import Stage1Pipeline
from app.schemas import GoalLogLabel, ResearchGoal, ResearchLog

logger = logging.getLogger(__name__)

_DEFAULT_DATA_DIR = "data/synthetic"


def _dynamic_candidate_size(corpus_size: int, top_k: int) -> int:
    """Candidate pool size scales with corpus — not hardcoded at 30.

    Corpus size   Ratio   Example (top_k=10)
    ──────────────────────────────────────────
    ≤  20         80 %    16
    ≤  50         60 %    30
    ≤ 100         50 %    50
    > 100         40 %    40+
    Always ≥ top_k.
    """
    if corpus_size <= 20:
        ratio = 0.80
    elif corpus_size <= 50:
        ratio = 0.60
    elif corpus_size <= 100:
        ratio = 0.50
    else:
        ratio = 0.40
    return max(top_k, int(corpus_size * ratio))

# ── Baseline configuration table ──────────────────────────────────────────────

STAGE1_BASELINE_CONFIGS: dict[str, dict] = {
    "dense": {
        "use_expansion": False,
        "disable_lexical_gate": True,
    },
    "dense_expand": {
        "use_expansion": True,
        "disable_lexical_gate": True,
    },
    "ours": {
        "use_expansion": True,
        "disable_lexical_gate": False,
    },
    "ours_wo_lexical_gate": {
        "use_expansion": True,
        "disable_lexical_gate": True,
    },
}


def load_data(data_dir: str):
    goals_path = Path(data_dir) / "goals.json"
    if goals_path.exists():
        logger.info("Loading dataset from %s", data_dir)
        _, goals, logs, labels = load_dataset_from_json(data_dir)
    else:
        logger.info("No dataset found at %s. Generating small dataset...", data_dir)
        ds = build_dataset(small_mode=True, seed=42)
        goals, logs, labels = ds.goals, ds.logs, ds.labels
    return goals, logs, labels


def main() -> None:
    parser = argparse.ArgumentParser(description="Run Stage 1 Retrieval Experiment")
    parser.add_argument("--user_id", default=None)
    parser.add_argument("--goal_id", default=None)
    parser.add_argument("--top_k", type=int, default=10)
    parser.add_argument("--candidate_size", type=int, default=None, help="Number of candidates to retrieve in Stage 1 (dense stage)")
    parser.add_argument(
        "--expand", action="store_true",
        help="[deprecated] Use --baseline hybrid_expand or ours instead. "
             "When --baseline=ours, this flag still forces expansion.",
    )
    parser.add_argument("--auto", action="store_true", help="Auto-pick first user/goal")
    parser.add_argument("--data_dir", default=_DEFAULT_DATA_DIR)
    parser.add_argument(
        "--real_embeddings", action="store_true",
        help="Use Gemini Embedding API (requires GEMINI_API_KEY)",
    )
    parser.add_argument(
        "--baseline",
        choices=list(STAGE1_BASELINE_CONFIGS.keys()),
        default="ours",
        help="Baseline: dense | dense_expand | ours | ours_wo_lexical_gate (default: ours)",
    )
    parser.add_argument(
        "--save_result", action="store_true",
        help="Save result to results/stage1/{goal_id}_{baseline}.json",
    )
    parser.add_argument(
        "--result_path", type=str, default=None,
        help="Custom result save path (overrides default results/stage1/ location)",
    )
    parser.add_argument(
        "--dense_threshold", type=float, default=None,
        help="Dense score threshold for candidate admission (e.g. 0.90). "
             "When set, only logs with normalized dense_score >= threshold enter the pipeline.",
    )
    args = parser.parse_args()

    goals, logs, labels = load_data(args.data_dir)

    # ── Resolve target goal ────────────────────────────────────────────────────
    if args.auto or (args.user_id is None and args.goal_id is None):
        target_goal = goals[0]
    elif args.goal_id:
        target_goal = next((g for g in goals if g.goal_id == args.goal_id), None)
        if target_goal is None:
            logger.error("goal_id=%s not found.", args.goal_id)
            sys.exit(1)
    else:
        target_goal = next((g for g in goals if g.user_id == args.user_id), None)
        if target_goal is None:
            logger.error("No goals found for user_id=%s.", args.user_id)
            sys.exit(1)

    user_id = target_goal.user_id
    user_logs = [l for l in logs if l.user_id == user_id]
    user_labels = [
        lb for lb in labels
        if lb.user_id == user_id and lb.goal_id == target_goal.goal_id
    ]

    logger.info(
        "User: %s | Goal: %s (%s) | Logs: %d",
        user_id, target_goal.goal_id, target_goal.title, len(user_logs),
    )

    # ── Baseline config ────────────────────────────────────────────────────────
    baseline = args.baseline
    bcfg = dict(STAGE1_BASELINE_CONFIGS[baseline])  # copy

    # --expand back-compat: forces expansion for 'ours' baseline
    if args.expand and baseline == "ours":
        bcfg["use_expansion"] = True

    cfg = DEFAULT_CONFIG.stage1
    cfg.retrieval.top_k = args.top_k
    
    if args.candidate_size is not None:
        cfg.retrieval.candidate_size = args.candidate_size
    else:
        cfg.retrieval.candidate_size = _dynamic_candidate_size(len(user_logs), args.top_k)

    pipeline = Stage1Pipeline(
        config=cfg,
        use_real_embeddings=args.real_embeddings,
        disable_lexical_gate=bcfg["disable_lexical_gate"],
        dense_threshold=args.dense_threshold,
    )
    pipeline.index(user_logs)
    result = pipeline.run(target_goal, use_expansion=bcfg["use_expansion"])

    k = args.top_k
    print("\n" + "=" * 60)
    print(f"Stage 1  |  Goal: {result.goal.title}")
    print(f"Baseline : {baseline}")
    print(f"Category : {target_goal.goal_id}")
    print(f"Query    : {result.query_text}")
    print(f"Expand   : {result.used_expansion}")
    print(f"Corpus   : {len(user_logs)} logs")
    print("=" * 60)

    print(f"\n[Top-{k} Selected Logs]")
    for r in result.selected_logs:
        strength = r.log.metadata.get("evidence_strength", "-")
        reason = r.admission_reason or "-"
        print(f"  [{r.rank:2d}] score={r.final_score:.4f}  {r.log.date}  [{strength}]  {r.log.title}")
        print(f"       admission: {reason}")

    if user_labels:
        all_types = {l.activity_type for l in user_logs}

        # ── Layer 1: Candidate pool metrics ───────────────────────────────────
        cand_metrics = compute_candidate_metrics(result.candidates, user_labels)

        print(f"\n[Layer 1: Candidate Pool  (top-{cand_metrics['candidate_size']})]")
        print(f"  {'relevant_in_pool':<28} {cand_metrics['relevant_in_pool']} / {cand_metrics['relevant_total']}")
        print(f"  {'candidate_recall':<28} {cand_metrics['candidate_recall']:.4f}  ← retrieval이 관련 로그를 담았나?")
        print(f"  {'candidate_precision':<28} {cand_metrics['candidate_precision']:.4f}  ← 후보 중 관련 로그 비율")
        print(f"  {'candidate_f1':<28} {cand_metrics['candidate_f1']:.4f}")

        # ── Layer 2: Selected (final top-K) metrics ───────────────────────────
        metrics = compute_all_metrics(
            result.ranked_logs, user_labels,
            k=k,
            all_activity_types=all_types,
            selected_logs=result.selected_logs,
        )
        s_prec = metrics["selected_precision"]
        s_count = metrics["selected_count"]
        fpr = metrics["false_positive_rate"]
        f1 = metrics[f"f1@{k}"]

        print(f"\n[Layer 2: Final Selected  (top-{k})]")
        print(f"  {'recall@'+str(k):<28} {metrics[f'recall@{k}']:.4f}  ← 최종 선택에서 관련 로그 회수율")
        print(f"  {'precision@'+str(k):<28} {metrics[f'precision@{k}']:.4f}")
        print(f"  {'selected_count':<28} {s_count}")
        print(f"  {'selected_precision':<28} {s_prec:.4f}  ← 최종 선택의 정확도")
        print(f"  {'f1@'+str(k):<28} {f1:.4f}")
        print(f"  {'false_positive_rate':<28} {fpr:.4f}")
        print(f"  {'mrr':<28} {metrics['mrr']:.4f}")
        print(f"  {'ndcg@'+str(k):<28} {metrics[f'ndcg@{k}']:.4f}")
        print(f"  {'diversity_coverage':<28} {metrics['diversity_coverage']:.4f}")

        # ── Bottleneck diagnosis ──────────────────────────────────────────────
        cr = cand_metrics["candidate_recall"]
        sp = s_prec
        print(f"\n[Bottleneck Diagnosis]")
        if cr < 0.70:
            print(f"  [!] candidate_recall={cr:.2f} — retrieval 단계에서 관련 로그를 놓치고 있음")
            print(f"     → dense query (goal summary / core_intents) 점검 필요")
        else:
            print(f"  [v] candidate_recall={cr:.2f} — retrieval 충분히 recall 확보")
        if sp < 0.60:
            print(f"  [!] selected_precision={sp:.2f} — reranker/filter 단계에서 노이즈 제거 부족")
            print(f"     → reranker weights, negative veto, relevance threshold 점검 필요")
        else:
            print(f"  [v] selected_precision={sp:.2f} — reranker precision 양호")

        # ── Label distribution ────────────────────────────────────────────────
        label_map = {lb.log_id: lb.label for lb in user_labels}
        dist: dict[str, int] = {}
        for r in result.selected_logs:
            lbl = label_map.get(r.log_id, "unknown")
            dist[lbl] = dist.get(lbl, 0) + 1
        print(f"\n[Label dist in selected] {dist}")

        # ── Debug Log Export ──────────────────────────────────────────────────
        debug_file = Path("debug_retrieval.log")
        with debug_file.open("w", encoding="utf-8") as f:
            f.write(f"=== Stage 1 Debug Log ===\n")
            f.write(f"Goal ID: {target_goal.goal_id}\n")
            f.write(f"Goal Title: {target_goal.title}\n\n")

            f.write("--- [1] 정답 로그 (Ground Truths for this Goal) ---\n")
            relevant_log_ids = {lb.log_id for lb in user_labels if lb.label in ("high", "medium", "relevant")}
            for lb in user_labels:
                if lb.label in ("high", "medium", "relevant"):
                    log_obj = next((l for l in user_logs if l.log_id == lb.log_id), None)
                    if log_obj:
                        f.write(f"[{lb.label.upper()}] ID: {log_obj.log_id} | Title: {log_obj.title}\n")
                        f.write(f"    Content: {log_obj.content}\n\n")

            f.write("--- [2] Dense Retrieval (Layer 1 Candidate Pool) 선택 로그 ---\n")
            for i, cand in enumerate(result.candidates, 1):
                is_gt = "O" if cand.log_id in relevant_log_ids else "X"
                f.write(f"{i:2d}. [GT: {is_gt}] ID: {cand.log_id} | Title: {cand.log.title} | Score: {cand.dense_score:.4f}\n")
                f.write(f"    Content: {cand.log.content}\n\n")
                
            if hasattr(result, "expanded_query") and result.expanded_query and hasattr(result.expanded_query, "dense_queries"):
                f.write("--- [3] 개별 쿼리별 상위 검색 결과 (Before Pooling) ---\n")
                cand_size = cand_metrics['candidate_size']
                for q in result.expanded_query.dense_queries:
                    f.write(f"\n>> 쿼리: {q}\n")
                    q_candidates = pipeline._retriever._dense.retrieve(q, top_n=cand_size)
                    for i, cand in enumerate(q_candidates, 1):
                        is_gt = "O" if cand.log_id in relevant_log_ids else "X"
                        f.write(f"  {i:2d}. [GT: {is_gt}] ID: {cand.log_id} | Title: {cand.log.title} | Score: {cand.dense_score:.4f}\n")
            
        print(f"\n[Debug Log saved] {debug_file.absolute()}")

        if args.save_result:
            from app.evaluation.result_writer import save_stage1_result
            path = save_stage1_result(
                goal_id=target_goal.goal_id,
                baseline=baseline,
                metrics={
                    f"recall@{k}": metrics[f"recall@{k}"],
                    f"precision@{k}": metrics[f"precision@{k}"],
                    "selected_count": s_count,
                    "selected_precision": s_prec,
                    f"f1@{k}": f1,
                    "false_positive_rate": fpr,
                    "mrr": metrics["mrr"],
                    f"ndcg@{k}": metrics[f"ndcg@{k}"],
                    "diversity_coverage": metrics["diversity_coverage"],
                    "candidate_count": cand_metrics["candidate_size"],
                    "admitted_count": len(result.selected_logs),
                },
                selected_log_ids=[r.log_id for r in result.selected_logs],
                selected_titles=[r.log.title for r in result.selected_logs],
                extra={
                    "baseline_config": {k2: str(v) for k2, v in bcfg.items()},
                    "dense_threshold": args.dense_threshold,
                },
                result_path=args.result_path,
            )
            print(f"\n[Result saved] {path}")
    else:
        print("\n[No labels found for this goal — skipping metrics]")


if __name__ == "__main__":
    main()
